# Generated by Django 3.2.4 on 2023-01-28 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pracownik_app', '0003_recenzja_ocena'),
    ]

    operations = [
        migrations.AddField(
            model_name='ksiazka',
            name='Zdjecie',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
