# Generated by Django 3.2.4 on 2023-01-30 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pracownik_app', '0005_ksiazka_opis'),
    ]

    operations = [
        migrations.AddField(
            model_name='zamowienie',
            name='Adres',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
