# Generated by Django 3.2.4 on 2023-01-30 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pracownik_app', '0006_zamowienie_adres'),
    ]

    operations = [
        migrations.AddField(
            model_name='zamowienie',
            name='LiczbaKs',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
